version: '3.1'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: lineschool
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    kvs:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
    commander:
        image: rediscommander/redis-commander
        restart: always
        environment:
            REDIS_HOSTS: kvs
        ports:
            - 8081:8081
