version: '3.1'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: lineschool
        ports:
            - 5901:5901
    adminer:
        image: adminer
        restart: always
        ports:
            - 9000:8080
